### ISSUE TITLE
Source incomplete

### ISSUE THREAD

**Issue by limelect** [rogerinnova/Delphi-Firemonkey-Dunit#2]
Can you include in source "Delphi 3_5 Source Code"
And a few more missing
Source incomplete

**Comment by rogerinnova** [comment]
While I originally (4 years ago) tried to provide full project code it is possible that some contamination of project references crept in when updating from my code base. Your reference Delphi 3_5 refers to my code base library directories which are often included in project search parameter. I would expect that removing the reference would resolve the issue. Which project are you interested in? If you can give me the names of functions or procedures that are unresolved I should be able to help you.

**Comment by limelect** [comment]
I wanted to compile converter
i downloaded https://github.com/e-delphi/VCL2FMX
which is Fork of you.
I was wandering the differences.
AND SPECIALLY the instruction you use like #delete#  EMPTY and so on......
I never found the instructions EXACT meaning .
Can yo elaborate on that?
As for 3.5 you use it all over.

**Comment by limelect** [comment]
PLz see issue 4 on the above project
I wanted to know if you have this problem

**Comment by rogerinnova** [comment]
This Project was originally published as an ADUG Demonstration in 2013 on the page

http://www.innovasolutions.com.au/delphistuf/ADUGVCLtoFMXConv.htm

That page has a description of the code and the Zip File there contains my latest compiled version.

The utility was then used in 2014 to generate a DUnit testing framework for FMX platforms.
http://docs.innovasolutions.com.au/Docs/ADUGDelphi/ADUGDecember2014.html
The converter code was mentioned and provided as it assisted in that project.

The code base was added to github in 2016 when I published the Android version of DUnit but I have not used the converter since the initial 
form was created in 2016 and I do not think I have made any changes to it since 2014. I find it much easier to design a Firemonkey form from 
scratch.

I published a .chm help file with the GitHub post but I now note that Microsoft security restrictions now make this useless.


Today I have now uploaded the help information to

http://www.innovasolutions.com.au/VCL_To_FiremonkeyConverter_Help/

so you can get answers to #Delete# etc (see also below)

I have had nothing to do with the fork so I do not know how much is changed.
Clearly they are targeting much later versions of Delphi than I was if the want to port LiveBindings

I hope this helps

Cheers Roger





On 15/09/2019 4:15 pm, limelect wrote:
> I wanted to compile converter
> i downloaded https://github.com/e-delphi/VCL2FMX
> which is Fork of you.
> I was wandering the differences.
> AND SPECIALLY the instruction you use like #delete# EMPTY and so on......

To Remove a property so the error warnings are not generated then replace it with #Delete#
Eg.
Font.Color=#Delete#



When a Section is not found for a VCL component a default section will be generated

[TLabel]
Empty=Add Transformations
Top=Position.Y
Left=Position.X
